# Uncomment the next line to define a global platform for your project

platform :ios, '13.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.rakops.com/MobileTracking/Specs.git'

target 'RADAdvertiserDemo' do
  
  use_frameworks!
  pod 'RADAttribution'
  
end
