platform :ios, '11.0'

use_frameworks!

target 'RADAttribution_Example' do
  
  pod 'RADAttribution', :path => '../'
  pod 'Sourcery'

  target 'RADAttribution_Tests' do
    inherit! :search_paths
  end
  
end
