platform :ios, '11.0'

use_frameworks!

target 'RakutenAdvertisingAttribution_Example' do
  
  pod 'RADAttribution', :path => '../'
  pod 'Sourcery'

  target 'RakutenAdvertisingAttribution_Tests' do
    inherit! :search_paths
  end
  
end
