included:
  - RakutenAdvertisingAttribution/Source
  - Example/RakutenAdvertisingAttribution
excluded:
  - RakutenAdvertisingAttribution/Source/Models/SourceryGenerated
disabled_rules:
  - superfluous_disable_command
line_length: 
  warning: 150
  error: 250
  ignores_function_declarations: false 
  ignores_comments: true
  ignores_urls: true
private_over_fileprivate: no
identifier_name:
  min_length: # only min_length
    warning: 1 # only warning